language: node_js
node_js:
- 8.9.4
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_25e713513946_key -iv $encrypted_25e713513946_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
addons:
  ssh_known_hosts: "$IP"
install:
- npm install
before_script:
script:
- npm run build
after_script:
- pwd
- scp -r dist/  root@$IP:/opt/nginx/
branches:
  only:
  - master
env:
  global:
